export const normalizedPublicAssets = {
  heroGraphic: '/assets/hero-graphic.png',
  googleLogo: '/assets/logo-google.png',
  dashbookingWordmark: '/assets/dashbooking-wordmark.png',
  freeTag: '/assets/free-tag.png',
  cloverTerminal: '/assets/clover-terminal.png',
  poyntTerminal: '/assets/poynt-terminal.png',
  hero: {
    staffAmy: '/assets/hero/staff-01.png',
    staffBella: '/assets/hero/staff-02.png',
    staffChloe: '/assets/hero/staff-03.png',
    businessProfileLead: '/assets/hero/business-profile-01-soft-pink-nails.png',
    businessProfileInterior: '/assets/hero/business-profile-02-salon-interior.png',
    businessProfileFloral: '/assets/hero/business-profile-03-blue-floral-nails.png',
  },
  aiReceptionist: {
    checkCurrentAppoinment: '/assets/ai-receptionist/check-current-appoinment.mp3',
    confirmAddress: '/assets/ai-receptionist/confirm-address.mp3',
    lateAppointment: '/assets/ai-receptionist/late-appointment.mp3',
    newAppoinment: '/assets/ai-receptionist/new-appoinment.mp3',
    reschedulingAppoinment: '/assets/ai-receptionist/rescheduling-appoinment.mp3',
    customerCaller: '/assets/ai-receptionist/customer-caller.png',
    headsetReceptionist: '/assets/ai-receptionist/staff-01-headset-receptionist.png',
    beautyProfessional: '/assets/ai-receptionist/staff-02-beauty-professional.png',
    salonSupport: '/assets/ai-receptionist/staff-03-salon-support.png',
    robotPortrait: '/assets/ai-receptionist/ai-receptionist-robot.png',
  },
  journey: {
    successChime: '/assets/journey/success-chime.wav',
  },
  googleReviews: {
    salonPhoto: '/assets/hero/business-profile-02-salon-interior.png',
  },
  websiteDesign: {
    laptopYourWay: '/assets/website-design/website-mockups/your-way-nail-spa-laptop-mockup-v3.png',
    mobileYourWay: '/assets/website-design/website-mockups/your-way-nail-spa-mobile-website-mockup-v3.png',
    laptopHestia: '/assets/website-design/website-mockups/hestia-nail-bar-laptop-mockup-v3.png',
    laptopLeva: '/assets/website-design/website-mockups/leva-nails-spa-laptop-mockup-v3.png',
    laptopModernChic: '/assets/website-design/website-mockups/modern-chic-nail-studio-laptop-mockup-v3.png',
    laptopKozy: '/assets/website-design/website-mockups/kozy-nail-studio-laptop-mockup-v3.png',
    laptopJoyOfNails: '/assets/website-design/website-mockups/joy-of-nails-laptop-mockup-v3.png',
    laptopBmNailsBar: '/assets/website-design/website-mockups/bm-nails-bar-laptop-mockup-v3.png',
    googleSearchAd: '/assets/website-design/google-ads/google-search-ad-for-your-way-nail-spa-v3.png',
    googleProfileCard: '/assets/website-design/google-ads/your-way-nail-spa-ui-card-v3.png',
    interiorCard: '/assets/website-design/support-cards/luxurious-nail-salon-interior-card-v3.png',
    portfolioCard: '/assets/website-design/support-cards/icy-blue-nail-portfolio-card-v3.png',
    menuCard: '/assets/website-design/support-cards/elegant-nail-salon-services-menu-card-v3.png',
  },
  posIntegration: {
    cloverFront: '/assets/pos-integration/terminals/clover-flex-waiting-to-pay.png',
    cloverPaid: '/assets/pos-integration/terminals/clover-flex-payment-successful.png',
    poynt: '/assets/pos-integration/terminals/poynt-smart-terminal.png',
  },
  addonFeatures: {
    giftCardIcon: '/assets/addon-features/icons/gift-card.svg',
    onlineDepositIcon: '/assets/addon-features/icons/online-deposit.svg',
  },
  leadCapture: {
    tabletCalendar: '/assets/lead-capture/tablet-calendar-mockup.png',
    phoneStorefront: '/assets/lead-capture/phone-mockup-your-lovely-nail-spa.png',
  },
} as const;
