import type { LandingContent } from '@/content/types';
import { dashbookingLeadInterestValues } from '@/content/lead-capture';
import { googlePartnersUrl } from '@/content/shared';

export const dashbookingLandingContentEn: LandingContent = {
  locale: 'en',
  metadata: {
    title: 'Dash Booking for nail and beauty salons',
    description: 'Google Booking, pay-as-you-go pricing, salon management, and optional add-ons.',
  },
  header: {
    nav: [
      { label: 'Pricing', href: '#pricing' },
    ],
    cta: 'Sign up free',
    homeAriaLabel: 'Go to Dash Booking home',
    navAriaLabel: 'Page sections',
    localeSwitcherAriaLabel: 'Switch language',
    partnerPillLabel: 'Google Authorized Partners List',
  },
  hero: {
    eyebrow: 'Book from Google',
    headlineLead: 'No customers,',
    headlineAccent: 'no fee.',
    handwrittenNote: 'Grow your salon with Google',
    subtitle:
      'Customers book right on Google, with no phone call. Appointments sync to the salon, so you spend less time answering the phone and writing them down.',
    chips: [{ label: 'Book on Google' }, { label: 'Appointments sync' }, { label: 'Less writing' }],
    partnerProofLead: 'Partnering with',
    partnerProofHighlight: '4,000+',
    partnerProofNoun: 'salons',
    partnerProofTail: 'across the',
    partnerProofPlace: 'US and Canada',
    primaryCta: 'Get advice for your salon',
    primaryCtaHref: '#lead-capture',
    toggleWithoutLabel: 'Without Dash',
    toggleWithLabel: 'With Dash',
    toggleAriaLabel: 'Compare booking with and without Dash',
    previewAriaLabel: 'Illustration of Google and the salon appointment calendar',
    googleIllustrationLabel: 'Illustration of the customer experience on Google',
    withoutDashExampleLabel: 'Illustration of a salon that has not turned on online booking',
    calendarDateLabel: 'Wed, Sep 16, 2024',
    calendarTodayLabel: 'Today',
    calendarHeading: "Today's appointments",
    emptySlotLabel: 'Empty',
    staff: [
      { id: 'amy', name: 'Amy', role: 'Nail Artist' },
      { id: 'bella', name: 'Bella', role: 'Nail Technician' },
      { id: 'chloe', name: 'Chloe', role: 'Nail Technician' },
    ],
    withoutDash: {
      annotations: [
        { id: 'customer-must-call', title: 'Customers need to call to book', anchor: 'call-button' },
        { id: 'manual-entry', title: 'The salon answers the phone and enters appointments by hand', anchor: 'calendar-empty' },
      ],
    },
    withDash: {
      annotations: [
        { id: 'customer-books-online', title: 'Customers book right on Google', anchor: 'book-online' },
        { id: 'appointments-sync', title: 'Appointments sync to the salon', anchor: 'calendar-fill' },
      ],
    },
    businessProfile: {
      name: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '225',
      category: 'Nail salon',
      hours: 'Open · Closes 7 p.m.',
      address: 'Roblin Blvd 5905 H, Winnipeg, MB R3R 0G8',
      morePhotosLabel: '+12',
      tabs: {
        overview: 'Overview',
        reviews: 'Reviews',
        photos: 'Photos',
        services: 'Services',
      },
      actions: {
        bookOnline: 'Book online',
        website: 'Website',
        directions: 'Directions',
        save: 'Save',
        share: 'Share',
        call: 'Call',
      },
      reviewsRow: '225 Reviews',
    },
  },
  bookingJourney: {
    titleLead: 'Clients book.',
    titleAccent: 'Dash handles the rest.',
    handwrittenLeft: 'Less chasing.',
    handwrittenRight: 'More time with clients.',
    ariaLabel: 'How Dash helps from the first booking to the next client',
    muteLabel: 'Mute sounds',
    unmuteLabel: 'Unmute sounds',
    nodes: [
      { id: 'discover', title: 'A new client finds you', benefit: 'Right when they’re looking' },
      { id: 'book-online', title: 'They pick a time and book', benefit: 'No calls. No back-and-forth.' },
      { id: 'calendar', title: 'The booking lands in Dash', benefit: 'Nothing to enter twice' },
      { id: 'reminder', title: 'Dash reminds them before they come', benefit: 'Fewer forgotten appointments' },
      { id: 'completed', title: 'They show up. You do what you do best.', benefit: 'A smoother day at the salon' },
      { id: 'review', title: 'After the visit, Dash asks for a review', benefit: 'No chasing clients for feedback' },
      { id: 'growth', title: 'Good reviews bring in the next client', benefit: 'And your calendar keeps filling up' },
    ],
    discover: {
      searchQuery: 'nail salon near me',
      salonName: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '(225)',
      category: 'Nail Salon',
      hours: 'Open',
    },
    booking: {
      heading: 'Book Appointment',
      service: 'Gel Manicure',
      staff: 'Any Staff',
      date: 'Wed, Sep 16',
      time: '10:00 AM',
      cta: 'Book Now',
    },
    calendar: {
      dateLabel: 'Wed, Sep 16, 2024',
    },
    reminder: {
      timeLabel: 'Today 9:00 AM',
      greeting: 'Hi Sarah!',
      body: 'Your appointment at Your Lovely Salon is tomorrow at 10:00 AM.',
      closing: 'See you soon!',
      sentLabel: 'Reminder sent',
    },
    completed: {
      heading: 'Appointment completed!',
      thanks: 'Thanks for visiting Your Lovely Salon!',
      statusLabel: 'Completed',
    },
    review: {
      timeLabel: 'Today 2:30 PM',
      message: 'Thanks for visiting! How was your experience at Your Lovely Salon?',
      cta: 'Write a review',
    },
    growth: {
      line1: 'Happy clients',
      line2: 'Good reviews',
      line3: 'New bookings',
    },
  },
  aiReceptionist: {
    eyebrow: 'AI Receptionist',
    headlineLead: 'Busy with a client?',
    headlineAccent: 'Dash can answer.',
    subtitle: 'Handles calls and books appointments, even when you are busy.',
    benefits: [
      { title: 'Never miss a call', body: 'Answers when you cannot.' },
      { title: 'Turns calls into bookings', body: 'Appointments go straight into Dash.' },
      { title: 'Always ready', body: 'Day, night, weekends.' },
    ],
    mobileChips: ['Answers calls 24/7', 'Books into your calendar'],
    costTeaser: 'About 1/10 the cost of a traditional receptionist*',
    costNote: 'Coverage comparison, not a public price list.',
    askLinkLabel: 'Ask about AI Receptionist',
    liveCallLabel: 'Live booking call',
    playRealCallLabel: 'Play',
    pauseLabel: 'Pause',
    soundOnLabel: 'Sound on',
    soundOffLabel: 'Sound off',
    customerLabel: 'Customer',
    customerCaption: 'Calls your salon',
    aiLabel: 'Dash AI Receptionist',
    aiCaption: 'Answers. Books. Done.',
    calendarDayLabel: 'Day',
    calendarWeekLabel: 'Week',
    serviceValue: 'Pedicure',
    anyStaffLabel: 'Any staff',
    firstVisitLabel: 'First visit',
    asapLabel: 'ASAP',
    transferLabel: 'Or connect to a person',
    checkingLabel: 'Checking availability',
    availableLabel: 'Available',
    selectedLabel: 'Selected',
    namePendingLabel: 'New client',
    notesNoneLabel: 'No special requests',
    bookedLabel: 'Booked',
    callCompleteLabel: 'Call complete',
    handwrittenNote: 'Call turns into a booking — automatically!',
    scenariosHeading: 'Hear more real call scenarios',
    scenariosSupport: 'Same natural conversations. Different situations.',
    scenariosToggleLabel: 'Hear more real scenarios',
    scenariosCollapseLabel: 'Hide extra scenarios',
    staff: [
      { id: 'amy', name: 'Amy' },
      { id: 'lisa', name: 'Lisa' },
      { id: 'mai', name: 'Mai' },
    ],
    scenarios: [
      { id: 'check-current-appoinment', title: 'Check Appointment', description: 'Looks up an existing booking.' },
      { id: 'confirm-address', title: 'Confirm Address', description: 'Shares your salon details.' },
      { id: 'late-appointment', title: 'Running Late', description: 'Handles a late arrival.' },
      { id: 'rescheduling-appoinment', title: 'Reschedule', description: 'Changes an appointment.' },
    ],
    ariaLabel: 'Dash AI receptionist live booking call demo',
  },
  googleReviews: {
    eyebrow: 'Google Reviews',
    headlineLead: 'Integrated AI replies to',
    headlineGoogle: 'Google',
    headlineTail: 'Reviews',
    subtitle: 'Dash helps you reply to reviews faster, keeping your Google profile active and professional.',
    benefits: [
      { id: 'auto-reply', title: 'Auto replies', body: '' },
      { id: 'maps-seo', title: 'Stronger presence on Google Maps', body: '' },
      { id: 'google-connect', title: 'Connected directly to your Google Business page', body: '' },
      { id: 'included', title: 'Included in Dash', body: 'No extra charges.' },
    ],
    salonName: 'Your Lovely Salon',
    ratingValue: '4.8',
    reviewCount: '(128 reviews)',
    categoryLocation: 'Beauty Salon · Winnipeg, MB',
    connectedLabel: 'Google Business connected',
    syncLabel: 'Reviews sync automatically',
    reviewsHeading: 'Reviews',
    filters: [
      { id: 'all', label: 'All (128)' },
      { id: 'five', label: '5★ (98)' },
      { id: 'three', label: '3★ (22)' },
      { id: 'one', label: '1★ (8)' },
    ],
    selectedReviewHeading: 'Selected review',
    suggestedReplyHeading: 'Suggested reply',
    thinkingLabel: 'AI is thinking',
    replyLabel: 'Reply',
    repliedLabel: 'Replied',
    copyLabel: 'Copy reply',
    copiedLabel: 'Copied',
    emptyFilterLabel: 'No sample reviews in this rating.',
    previousReviewLabel: 'Previous review',
    nextReviewLabel: 'Next review',
    reviewsAriaLabel: 'Sample Google reviews',
    ariaLabel: 'Dash AI replies to Google reviews',
  },
  websiteDesign: {
    eyebrow: 'Grow your salon',
    titleLead: 'Custom Website Design &',
    titleGoogle: 'Google',
    titleTail: 'Ads',
    subtitle: 'Beautiful websites. More visibility. More bookings.',
    websiteEyebrow: 'Website Design',
    websiteTitle: 'A beautiful website for your salon',
    websiteBody: 'Turn your salon’s unique style into a stunning website that brings in more clients.',
    freeSeoLabel: 'Free SEO included',
    freeSeoExtra: '$0 extra',
    websiteBullets: [
      'Show your interior & atmosphere',
      'Display nail portfolio',
      'Present your menu & services',
      'Built for bookings',
    ],
    viewMoreLabel: 'View more websites',
    adsEyebrow: 'Google Ads Management',
    adsTitle: 'Show up first for “nails near me”',
    adsBody: 'When someone nearby searches nails near me, your salon can appear at the top of Google. We set up the ads. You get the bookings.',
    freeSetupLabel: 'Free Setup',
    freeSetupPrice: '$0',
    freeSetupNote: 'We build and launch the campaign for you.',
    creditLabel: 'Spend $600, Get $600',
    creditNote: 'FREE Google Ads credit to start',
    searchQuery: 'nail salon near me',
    bookedLabel: 'Booked',
    outcomes: [
      { title: 'Reach local customers', body: 'People searching near your salon' },
      { title: 'Get more qualified visits', body: 'Clicks from real intent' },
      { title: 'Turn searches into bookings', body: 'From Google to your chair' },
    ],
    galleryTitle: 'Real salon websites designed by Dash',
    gallerySubtitle: 'Modern. Elegant. Built for results.',
    viewWebsiteLabel: 'View website',
    prevLabel: 'Previous websites',
    nextLabel: 'Next websites',
    ariaLabel: 'Custom website design and Google Ads',
  },
  posIntegration: {
    eyebrow: 'POS Integration',
    titleLead: 'Checkout on Dash.',
    titleAccent: 'Payment goes to terminal.',
    subtitle: 'Clover Flex Gen 4 or Poynt Smart Terminal, fully connected to Dash.',
    benefits: [
      'Amount sends automatically',
      'No contract',
      'Cancel anytime',
      'Payment status syncs back',
      'Built for salons',
    ],
    amount: '114.98',
    addPaymentLabel: 'Add Payment',
    cashLabel: 'Cash',
    cardLabel: 'Card',
    giftCardLabel: 'Gift Card',
    otherLabel: 'Other',
    loyaltyLabel: 'Apply Loyalty',
    promotionsLabel: 'Apply Promotions',
    sendingLabel: 'Sending automatically…',
    processingLabel: 'Processing…',
    successTitle: 'Payment Successful!',
    completeTitle: 'Payment Complete',
    completeMeta: 'Apr 29, 2026  1:24 PM\nClover Flex •••• 4242',
    viewReceiptLabel: 'View Receipt',
    syncedTitle: 'Synced to Dash',
    syncedNote: 'Payment recorded automatically',
    chooseTitle: 'Choose Your Terminal',
    chooseSubtitle: 'Two great options. Fully integrated with Dash.',
    handwrittenNote: 'Same powerful integration. Choose what works for you.',
    clover: {
      id: 'clover',
      name: 'Clover Flex Gen 4',
      blurb: 'Portable. Powerful. Perfect for salons.',
      benefits: [
        'Fully integrated with Dash',
        'Accept tap, chip, and debit/credit',
        'Print or email receipts',
        'Fast and reliable',
      ],
      ctaLabel: 'Learn more about Clover',
      ctaHref: 'https://www.clover.com/',
    },
    poynt: {
      id: 'poynt',
      name: 'Poynt Smart Terminal',
      blurb: 'Smart. Flexible. All-in-one.',
      benefits: [
        'Fully integrated with Dash',
        'Accept tap, chip, and debit/credit',
        'Built-in receipt printer',
        'Modern and sleek design',
        'Perfect for growing salons',
      ],
      ctaLabel: 'Learn more about Poynt',
      ctaHref: 'https://poynt.com/',
    },
    cloverRentalLabel: 'Terminal rental',
    cloverRentalPrice: '$30 / month',
    cloverRates: ['Debit: $0.04 / transaction', 'Credit: Cost + 0.25%'],
    noContractLabel: 'No contract',
    cancelAnytimeLabel: 'Cancel anytime',
    ariaLabel: 'POS integration with Clover and Poynt',
  },
  addonFeatures: {
    eyebrow: 'Add-on Features',
    titleLead: 'Add-ons that make booking',
    titleAccent: 'smoother',
    handwrittenLeft: 'Flexible tools for a smoother business',
    handwrittenRight: 'More bookings. Happier customers.',
    giftCard: {
      title: 'Online Gift Card',
      tagline: 'Buy online. Send by email. Balance stored online.',
      steps: [
        { id: 'purchase', label: 'Purchase', shortLabel: 'Purchase', detail: 'Customer buys a gift card online.' },
        { id: 'generate', label: 'Create Gift Card', shortLabel: 'Create', detail: 'A digital gift card is generated.' },
        { id: 'email', label: 'Send by Email', shortLabel: 'Send', detail: 'Gift card is delivered to their inbox.' },
        { id: 'balance', label: 'Redeem Later', shortLabel: 'Redeem', detail: 'Balance is stored online and used at checkout.' },
      ],
      benefits: [
        { title: 'Sent by email', body: 'Instant delivery' },
        { title: 'No physical card', body: '100% digital' },
        { title: 'Balance saved online', body: 'Always accessible' },
      ],
      purchaseTitle: 'Buy a Gift Card',
      amountLabel: 'Amount',
      amounts: ['$25', '$50', '$100'],
      selectedAmount: '$50',
      recipientNameLabel: 'Recipient Name',
      recipientNamePlaceholder: 'Recipient name',
      recipientEmailLabel: 'Recipient Email',
      recipientEmailPlaceholder: 'name@example.com',
      messageLabel: 'Message (optional)',
      messagePlaceholder: 'Happy Birthday!',
      continueLabel: 'Continue',
      giftCardCaption: 'A gift for you',
      giftCardAmount: '$50',
      giftCardNote: 'Digital. Instant.',
      inboxLabel: 'Inbox',
      inboxTime: 'now',
      inboxTitle: 'A special gift for you',
      inboxAmountLabel: '$50 Gift Card',
      viewGiftCardLabel: 'View Gift Card',
      deliveredLabel: 'Delivered',
      balanceTitle: 'Card Balance',
      balanceAmount: '$50.00',
      shopServicesLabel: 'Shop Services',
      applyCheckoutLabel: 'Apply at Checkout',
      remainingLabel: 'Remaining balance',
      remainingAmount: '$25.00',
    },
    deposit: {
      title: 'Online Deposit',
      tagline: 'Take deposits online before the appointment.',
      steps: [
        { id: 'setup', label: 'Set Up', shortLabel: 'Set Up', detail: 'Enable and configure deposit settings.' },
        { id: 'booking', label: 'Customer Books', shortLabel: 'Books', detail: 'Deposit is required during checkout.' },
        { id: 'payment', label: 'Deposit Payment', shortLabel: 'Payment', detail: 'Customer pays deposit online.' },
        { id: 'confirmed', label: 'Booking Confirmed', shortLabel: 'Confirmed', detail: 'Appointment is secured with deposit.' },
      ],
      benefits: [
        { title: 'Reduce no-shows', body: 'More reliable revenue' },
        { title: 'Flexible setup', body: 'Works for your business' },
        { title: 'Secure bookings', body: 'Safe and encrypted' },
      ],
      enableLabel: 'Enable Online Deposit',
      requiredLabel: 'Deposit is required for',
      individualLabel: 'Individual Booking',
      groupLabel: 'Group Booking',
      depositAmountLabel: 'Deposit Amount',
      depositAmountValue: '50',
      depositRateLabel: 'Deposit Rate (%)',
      depositRateValue: '25%',
      applyForLabel: 'Apply For',
      applyForValue: 'All Services',
      bookingTitle: 'Your Booking',
      bookingEditLabel: 'Edit',
      serviceName: 'Gel Manicure',
      serviceMeta: '60 min · $120',
      depositRequiredLabel: 'Deposit required',
      depositRequiredAmount: '$50.00',
      proceedLabel: 'Proceed to Payment',
      paymentTitle: 'Payment',
      secureLabel: 'Secure payment',
      cardMask: 'Card ending 4242',
      payDepositAmount: 'Pay $50.00 deposit',
      payDepositLabel: 'Pay Deposit',
      paymentNote: 'Your payment is secure and encrypted.',
      confirmedTitle: 'Booking Confirmed!',
      confirmedBody: 'Your appointment is secured with a deposit.',
      viewBookingLabel: 'View Booking',
      addToCalendarLabel: 'Add to Calendar',
    },
    ariaLabel: 'Optional add-on features for online gift cards and deposits',
  },
  leadCapture: {
    eyebrow: 'Talk to Dash',
    title: 'Ready to see if Dash fits your salon?',
    subtitle: 'Tell us a little about your salon. We’ll show you what makes sense for your business.',
    visualHeadlineLead: 'Let’s find the',
    visualHeadlineAccent: 'right solution',
    visualHeadlineTail: 'for your salon',
    visualBullets: ['Get personalized advice', 'Talk to a real person', 'No commitment'],
    visualNote: 'Your growth is our priority',
    visualBadgeLead: 'More bookings',
    visualBadgeTail: 'More happy clients',
    tabletAlt: 'Dash Booking appointment calendar on a tablet',
    phoneAlt: 'Your Lovely Nail Spa booking page on a phone',
    nameLabel: 'Full name',
    namePlaceholder: 'Emma Smith',
    businessLabel: 'Salon / Business name',
    businessPlaceholder: 'Glow Nail Studio',
    addressLabel: 'Address',
    addressPlaceholder: '5905 Roblin Blvd',
    regionLabel: 'Province / State',
    regionPlaceholder: 'MB',
    countryLabel: 'Country',
    countryPlaceholder: 'Canada',
    phoneLabel: 'Phone',
    phonePlaceholder: '(204) 555-0100',
    emailLabel: 'Email',
    emailPlaceholder: 'emma@example.com',
    cityLabel: 'City',
    cityPlaceholder: 'Winnipeg',
    interestLabel: 'What are you interested in?',
    interestPlaceholder: 'Select one',
    messageLabel: 'Message',
    messageHint: 'Optional',
    messagePlaceholder: 'Anything we should know before we call?',
    interestOptions: [
      { value: dashbookingLeadInterestValues[0], label: 'Booking System' },
      { value: dashbookingLeadInterestValues[1], label: 'AI Receptionist' },
      { value: dashbookingLeadInterestValues[2], label: 'Website + Google Ads' },
      { value: dashbookingLeadInterestValues[3], label: 'POS' },
      { value: dashbookingLeadInterestValues[4], label: 'Not sure yet' },
    ],
    submitLabel: 'Get advice for your salon',
    submittingLabel: 'Sending…',
    submittedLabel: 'Submitted',
    successKicker: 'Thanks!',
    successTitle: 'We got your request.',
    successBody: 'Someone from Dash will be in touch shortly.',
    successChips: [
      { title: 'Usually within', body: '1 business day' },
      { title: 'A real person', body: 'will contact you' },
      { title: 'Tailored advice', body: 'for your salon' },
    ],
    errorRetry: 'Something went wrong. Please try again.',
    requiredError: 'This field is required.',
    emailError: 'Please enter a valid email address.',
    phoneError: 'Please enter a valid phone number.',
    privacyNote: 'We’ll never share your info.',
    ariaLabel: 'Ask Dash for salon advice',
  },
  trust: {
    eyebrow: 'Google Authorized Partner',
    title: 'Dash Booking - Direct Google Partner',
    logoAlt: 'Google logo',
    partnerCtaLabel: 'Google booking partners list',
    partnerCtaHref: googlePartnersUrl,
    stats: [
      { value: '160M+', label: 'appointments' },
      { value: '150+', label: 'cities' },
      { value: '16', label: 'countries' },
      { value: '7+', label: 'languages' },
    ],
    statsAriaLabel: 'Dash Booking stats',
  },
  customerCities: {
    eyebrow: '',
    title: 'Salons using Dash Booking',
    cityCta: 'View salons in {city}',
    moreLabel: 'View more cities',
    lessLabel: 'Show fewer cities',
  },
  ai: {
    eyebrow: '',
    title: 'Integrated AI Receptionist',
    description: 'Answers calls and books appointments 24/7.',
    supportLine: 'English / French bilingual',
    price: '',
    priceLines: [
      '$300 setup one-time',
      '$30/month AI Access',
      '$20/month AI Phone Number',
      '$0.30/minute Call Time',
    ],
    demoTitle: 'Listen',
    demoIds: [
      'check-current-appoinment',
      'confirm-address',
      'late-appointment',
      'new-appoinment',
      'rescheduling-appoinment',
    ],
  },
  pricing: {
    eyebrow: 'Pricing',
    title: 'Pay As You Go',
    supportLine: 'No setup fee. No contract. No customer, no fee.',
    volumeLabel: 'Monthly online appointments',
    tiers: [
      {
        range: '0 completed online appointments',
        selectorLabel: '0',
        price: '$0 / month',
        detail: 'No online bookings yet — no monthly charge',
      },
      {
        range: '1 to 49 completed online appointments',
        selectorLabel: '<50',
        price: '$29 / month',
        detail: 'For 1–49 completed online bookings a month',
      },
      {
        range: '50 to 149 completed online appointments',
        selectorLabel: '<150',
        price: '$69 / month',
        detail: 'For 50–149 completed online bookings a month',
      },
      {
        range: '150 to 499 completed online appointments',
        selectorLabel: '<500',
        price: '$99 / month',
        detail: 'For 150–499 completed online bookings a month',
      },
      {
        range: '500 to 999 completed online appointments',
        selectorLabel: '<1000',
        price: '$149 / month',
        detail: 'For 500–999 completed online bookings a month',
      },
      {
        range: '1000+ completed online appointments',
        selectorLabel: '1000+',
        price: '$199 / month',
        detail: 'For 1,000+ completed online bookings a month',
      },
    ],
    selectorAriaLabel: 'Pricing tiers by appointment count',
    trustChips: ['No setup fee', 'No contract', 'Scales with your bookings'],
    smsNote: 'Optional ¢5 per SMS',
    processingFeeNote: '(3%) Processing fee will apply on credit card',
    ctaLabel: '',
  },
  includes: {
    eyebrow: '',
    title: 'Dash Booking Platform',
    cardsAriaLabel: 'Core Dash Booking platform features',
    cards: [
      {
        title: 'Appointment Calendar',
        description: 'Manage the calendar by day, staff, and booking source.',
      },
      {
        title: 'Client Management',
        description: 'Store client info, booking history, and notes.',
      },
      {
        title: 'Staff & Service Setup',
        description: 'Manage staff, services, pricing, and duration.',
      },
      {
        title: 'Booking Page / QR Code',
        description: 'Clients book by booking link, website, or QR code.',
      },
      {
        title: 'Group Booking',
        description: 'Take multiple clients in one booking.',
      },
      {
        title: 'Reporting & Analytics',
        description: 'Track bookings, revenue, and salon performance.',
      },
    ],
  },
  addOns: {
    eyebrow: '',
    title: 'Optional Add-on Features',
    supportLine: '',
    terminalTitle: 'Clover / Poynt Integration',
    terminalIntro: '',
    terminalBadge: '',
    terminalRates: ['Debit: $0.04 / transaction', 'Credit: Cost + 0.25%', 'Terminal rental: $30 / month'],
    terminalDisclaimer: '',
    terminalListAriaLabel: 'Supported payment terminals',
    optionalListAriaLabel: 'Optional add-ons',
    optionalItems: [
      {
        slug: 'website',
        name: 'SEO Website',
        price: '',
        description: '',
        ctaLabel: 'Template',
        ctaHref: 'https://websitetemplate.ca/',
      },
      {
        slug: 'google-business-profile',
        name: 'Manage Google Business Profile',
        price: '',
        description: 'Manage salon profile / reply to Google reviews',
      },
      {
        slug: 'online-deposits-gift-cards',
        name: 'Online Deposits & Gift Cards',
        price: '',
        description: '',
      },
      {
        slug: 'sell-products',
        name: 'Sell Products',
        price: '',
        description: '',
      },
      {
        slug: 'ai-social-media',
        name: 'AI Social Media',
        price: '',
        description: 'Coming soon',
      },
    ],
  },
  faq: {
    eyebrow: '',
    title: 'Q&A',
    items: [
      {
        question: 'Are cancel / no-shows charged?',
        answer: 'No.',
      },
      {
        question: 'Can I export my client list?',
        answer: 'Yes. Download Excel directly from the system.',
      },
      {
        question: 'Can I import client data?',
        answer: 'Yes. Dash Booking helps clean and import it.',
      },
      {
        question: 'Is there a contract?',
        answer: 'No. No Contract - No Setup Fee.',
      },
      {
        question: 'How many staff can use it?',
        answer: 'From 1 to 50+ staff.',
      },
      {
        question: 'How do monthly payments work?',
        answer: 'Credit Card, Void Cheque, or PayPal.',
      },
      {
        question: 'Which devices work?',
        answer: 'Dash Booking works with every device.',
      },
    ],
  },
  footer: {
    summary: 'All-in-one platform for beauty salon',
    rights: '© Dash Booking. All rights reserved.',
  },
};
