import type { LandingContent } from '@/content/types';
import { dashbookingLeadInterestValues } from '@/content/lead-capture';
import { googlePartnersUrl } from '@/content/shared';

export const dashbookingLandingContentFr: LandingContent = {
  locale: 'fr',
  metadata: {
    title: 'Dash Booking pour les salons de manucure et de beauté',
    description: 'Google Booking, tarification à l’usage, gestion du salon et fonctionnalités optionnelles.',
  },
  header: {
    nav: [
      { label: 'Tarifs', href: '#pricing' },
    ],
    cta: 'Inscription gratuite',
    homeAriaLabel: 'Aller à l’accueil de Dash Booking',
    navAriaLabel: 'Sections de la page',
    localeSwitcherAriaLabel: 'Changer de langue',
    partnerPillLabel: 'Liste des partenaires Google autorisés',
  },
  hero: {
    eyebrow: 'Réserver depuis Google',
    headlineLead: 'Pas de clients,',
    headlineAccent: 'pas de frais.',
    handwrittenNote: 'Faites grandir votre salon avec Google',
    subtitle:
      'Les clientes réservent directement sur Google, sans appeler. Les rendez-vous se synchronisent dans le salon : moins d’appels et moins de saisie à la main.',
    chips: [{ label: 'Réserver sur Google' }, { label: 'Agenda synchronisé' }, { label: 'Moins de saisie' }],
    partnerProofLead: 'Aux côtés de',
    partnerProofHighlight: '4 000+',
    partnerProofNoun: 'salons',
    partnerProofTail: 'aux',
    partnerProofPlace: 'États-Unis et au Canada',
    primaryCta: 'Recevoir des conseils pour le salon',
    primaryCtaHref: '#lead-capture',
    toggleWithoutLabel: 'Sans Dash',
    toggleWithLabel: 'Avec Dash',
    toggleAriaLabel: 'Comparer la réservation avec et sans Dash',
    previewAriaLabel: 'Illustration de Google et de l’agenda du salon',
    googleIllustrationLabel: 'Illustration de l’expérience cliente sur Google',
    withoutDashExampleLabel: 'Illustration d’un salon qui n’a pas activé la réservation en ligne',
    calendarDateLabel: 'mer. 16 sept. 2024',
    calendarTodayLabel: 'Aujourd’hui',
    calendarHeading: 'Rendez-vous du jour',
    emptySlotLabel: 'Libre',
    staff: [
      { id: 'amy', name: 'Amy', role: 'Nail Artist' },
      { id: 'bella', name: 'Bella', role: 'Nail Technician' },
      { id: 'chloe', name: 'Chloe', role: 'Nail Technician' },
    ],
    withoutDash: {
      annotations: [
        { id: 'customer-must-call', title: 'Les clientes doivent appeler pour réserver', anchor: 'call-button' },
        { id: 'manual-entry', title: 'Le salon répond au téléphone et saisit les rendez-vous à la main', anchor: 'calendar-empty' },
      ],
    },
    withDash: {
      annotations: [
        { id: 'customer-books-online', title: 'Les clientes réservent directement sur Google', anchor: 'book-online' },
        { id: 'appointments-sync', title: 'Les rendez-vous se synchronisent dans le salon', anchor: 'calendar-fill' },
      ],
    },
    businessProfile: {
      name: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '225',
      category: 'Nail salon',
      hours: 'Open · Closes 7 p.m.',
      address: 'Roblin Blvd 5905 H, Winnipeg, MB R3R 0G8',
      morePhotosLabel: '+12',
      tabs: {
        overview: 'Overview',
        reviews: 'Reviews',
        photos: 'Photos',
        services: 'Services',
      },
      actions: {
        bookOnline: 'Book online',
        website: 'Website',
        directions: 'Directions',
        save: 'Save',
        share: 'Share',
        call: 'Call',
      },
      reviewsRow: '225 Reviews',
    },
  },
  bookingJourney: {
    titleLead: 'Vos clients réservent.',
    titleAccent: 'Dash s’occupe du reste.',
    handwrittenLeft: 'Moins de suivis.',
    handwrittenRight: 'Plus de temps avec vos clients.',
    ariaLabel: 'Comment Dash accompagne chaque rendez-vous',
    muteLabel: 'Couper le son',
    unmuteLabel: 'Activer le son',
    nodes: [
      { id: 'discover', title: 'Un nouveau client vous trouve', benefit: 'Au moment où il cherche un salon' },
      { id: 'book-online', title: 'Il choisit son heure et réserve', benefit: 'Pas d’appels, pas d’allers-retours' },
      { id: 'calendar', title: 'Le rendez-vous arrive dans Dash', benefit: 'Rien à saisir deux fois' },
      { id: 'reminder', title: 'Dash lui rappelle son rendez-vous', benefit: 'Moins d’oublis, moins d’absences' },
      { id: 'completed', title: 'Le client arrive. Vous faites ce que vous faites de mieux.', benefit: 'Une journée plus simple au salon' },
      { id: 'review', title: 'Après la visite, Dash demande un avis', benefit: 'Pas besoin de relancer chaque client' },
      { id: 'growth', title: 'Les bons avis amènent le prochain client', benefit: 'Et l’agenda se remplit naturellement' },
    ],
    discover: {
      searchQuery: 'salon de manucure près de moi',
      salonName: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '(225)',
      category: 'Salon de manucure',
      hours: 'Ouvert',
    },
    booking: {
      heading: 'Prendre rendez-vous',
      service: 'Manucure gel',
      staff: 'N’importe quel staff',
      date: 'mer. 16 sept.',
      time: '10 h 00',
      cta: 'Réserver',
    },
    calendar: {
      dateLabel: 'mer. 16 sept. 2024',
    },
    reminder: {
      timeLabel: 'Aujourd’hui 9 h 00',
      greeting: 'Bonjour Sarah !',
      body: 'Votre rendez-vous chez Your Lovely Salon est demain à 10 h 00.',
      closing: 'À bientôt !',
      sentLabel: 'Rappel envoyé',
    },
    completed: {
      heading: 'Rendez-vous terminé !',
      thanks: 'Merci d’être venue chez Your Lovely Salon !',
      statusLabel: 'Terminé',
    },
    review: {
      timeLabel: 'Aujourd’hui 14 h 30',
      message: 'Merci pour votre visite ! Comment s’est passée votre expérience chez Your Lovely Salon ?',
      cta: 'Écrire un avis',
    },
    growth: {
      line1: 'Clients contents',
      line2: 'Bons avis',
      line3: 'Nouveaux rendez-vous',
    },
  },
  aiReceptionist: {
    eyebrow: 'Réceptionniste IA',
    headlineLead: 'Occupé avec un client ?',
    headlineAccent: 'Dash peut répondre.',
    subtitle: 'Répond aux appels et prend les rendez-vous, même quand vous êtes occupé.',
    benefits: [
      { title: 'Aucun appel manqué', body: 'Répond quand vous ne pouvez pas.' },
      { title: 'Transforme l’appel en rendez-vous', body: 'Les rendez-vous vont directement dans Dash.' },
      { title: 'Toujours disponible', body: 'Jour, nuit, week-end.' },
    ],
    mobileChips: ['Répond 24 h/24', 'Réserve dans le calendrier'],
    costTeaser: 'Environ 1/10 du coût d’une réceptionniste traditionnelle*',
    costNote: 'Comparaison de couverture, pas une grille tarifaire publique.',
    askLinkLabel: 'Demander pour la réceptionniste IA',
    liveCallLabel: 'Appel de réservation en direct',
    playRealCallLabel: 'Lecture',
    pauseLabel: 'Pause',
    soundOnLabel: 'Son activé',
    soundOffLabel: 'Son coupé',
    customerLabel: 'Cliente',
    customerCaption: 'Appelle votre salon',
    aiLabel: 'Réceptionniste IA Dash',
    aiCaption: 'Répond. Réserve. C’est fait.',
    calendarDayLabel: 'Jour',
    calendarWeekLabel: 'Semaine',
    serviceValue: 'Pédicure',
    anyStaffLabel: 'N’importe qui',
    firstVisitLabel: 'Première visite',
    asapLabel: 'Dès que possible',
    transferLabel: 'Ou passer à une personne',
    checkingLabel: 'Vérification des disponibilités',
    availableLabel: 'Disponible',
    selectedLabel: 'Sélectionné',
    namePendingLabel: 'Nouvelle cliente',
    notesNoneLabel: 'Aucune demande particulière',
    bookedLabel: 'Réservé',
    callCompleteLabel: 'Appel terminé',
    handwrittenNote: 'L’appel devient un rendez-vous — automatiquement !',
    scenariosHeading: 'Écouter d’autres appels réels',
    scenariosSupport: 'Mêmes conversations naturelles. Autres situations.',
    scenariosToggleLabel: 'Écouter d’autres scénarios réels',
    scenariosCollapseLabel: 'Masquer les scénarios',
    staff: [
      { id: 'amy', name: 'Amy' },
      { id: 'lisa', name: 'Lisa' },
      { id: 'mai', name: 'Mai' },
    ],
    scenarios: [
      { id: 'check-current-appoinment', title: 'Vérifier le rendez-vous', description: 'Retrouve une réservation existante.' },
      { id: 'confirm-address', title: 'Confirmer l’adresse', description: 'Donne les détails du salon.' },
      { id: 'late-appointment', title: 'En retard', description: 'Gère une arrivée tardive.' },
      { id: 'rescheduling-appoinment', title: 'Reprogrammer', description: 'Change un rendez-vous.' },
    ],
    ariaLabel: 'Démo d’appel de réservation avec la réceptionniste IA Dash',
  },
  googleReviews: {
    eyebrow: 'Avis Google',
    headlineLead: 'L’IA répond aux avis',
    headlineGoogle: 'Google',
    headlineTail: '',
    subtitle: 'Dash vous aide à répondre plus vite, pour un profil Google plus actif et plus professionnel.',
    benefits: [
      { id: 'auto-reply', title: 'Réponses automatiques', body: '' },
      { id: 'maps-seo', title: 'Meilleure présence sur Google Maps', body: '' },
      { id: 'google-connect', title: 'Connexion directe à la page Google du salon', body: '' },
      { id: 'included', title: 'Inclus dans Dash', body: 'Aucun frais supplémentaire.' },
    ],
    salonName: 'Your Lovely Salon',
    ratingValue: '4.8',
    reviewCount: '(128 avis)',
    categoryLocation: 'Salon de beauté · Winnipeg, MB',
    connectedLabel: 'Google Business connecté',
    syncLabel: 'Les avis se synchronisent automatiquement',
    reviewsHeading: 'Avis',
    filters: [
      { id: 'all', label: 'Tous (128)' },
      { id: 'five', label: '5★ (98)' },
      { id: 'three', label: '3★ (22)' },
      { id: 'one', label: '1★ (8)' },
    ],
    selectedReviewHeading: 'Avis sélectionné',
    suggestedReplyHeading: 'Réponse suggérée',
    thinkingLabel: 'L’IA réfléchit',
    replyLabel: 'Répondre',
    repliedLabel: 'Répondu',
    copyLabel: 'Copier la réponse',
    copiedLabel: 'Copié',
    emptyFilterLabel: 'Aucun avis d’exemple pour cette note.',
    previousReviewLabel: 'Avis précédent',
    nextReviewLabel: 'Avis suivant',
    reviewsAriaLabel: 'Exemples d’avis Google',
    ariaLabel: 'L’IA Dash répond aux avis Google',
  },
  websiteDesign: {
    eyebrow: 'Développez votre salon',
    titleLead: 'Site web sur mesure et',
    titleGoogle: 'Google',
    titleTail: 'Ads',
    subtitle: 'De beaux sites. Plus de visibilité. Plus de réservations.',
    websiteEyebrow: 'Conception de site',
    websiteTitle: 'Un beau site pour votre salon',
    websiteBody: 'Transformez le style unique de votre salon en un site qui attire plus de clientes.',
    freeSeoLabel: 'SEO inclus gratuitement',
    freeSeoExtra: '0 $ de plus',
    websiteBullets: [
      'Montrez l’intérieur du salon',
      'Portfolio de nails',
      'Menu et services',
      'Conçu pour réserver',
    ],
    viewMoreLabel: 'Voir plus de sites',
    adsEyebrow: 'Gestion Google Ads',
    adsTitle: 'Apparaissez en premier pour « nails near me »',
    adsBody: 'Quand quelqu’un près de chez vous cherche nails near me, votre salon peut s’afficher en tête de Google. Nous lançons les pubs. Vous recevez les réservations.',
    freeSetupLabel: 'Installation gratuite',
    freeSetupPrice: '0 $',
    freeSetupNote: 'Nous créons et lançons la campagne pour vous.',
    creditLabel: 'Dépensez 600 $, recevez 600 $',
    creditNote: 'Crédit Google Ads gratuit pour démarrer',
    searchQuery: 'nail salon near me',
    bookedLabel: 'Réservé',
    outcomes: [
      { title: 'Reach local customers', body: 'Des recherches près de votre salon' },
      { title: 'Get more qualified visits', body: 'Des clics avec une vraie intention' },
      { title: 'Turn searches into bookings', body: 'De Google à votre chaise' },
    ],
    galleryTitle: 'De vrais sites de salon conçus par Dash',
    gallerySubtitle: 'Moderne. Élégant. Fait pour convertir.',
    viewWebsiteLabel: 'Voir le site',
    prevLabel: 'Sites précédents',
    nextLabel: 'Sites suivants',
    ariaLabel: 'Conception de site web et Google Ads',
  },
  posIntegration: {
    eyebrow: 'Intégration POS',
    titleLead: 'Encaissement sur Dash.',
    titleAccent: 'Le paiement part au terminal.',
    subtitle: 'Clover Flex Gen 4 ou Poynt Smart Terminal, entièrement connecté à Dash.',
    benefits: [
      'Le montant part automatiquement',
      'Pas de contrat',
      'Annulation à tout moment',
      'Le statut revient dans Dash',
      'Conçu pour les salons',
    ],
    amount: '114.98',
    addPaymentLabel: 'Add Payment',
    cashLabel: 'Cash',
    cardLabel: 'Card',
    giftCardLabel: 'Gift Card',
    otherLabel: 'Other',
    loyaltyLabel: 'Apply Loyalty',
    promotionsLabel: 'Apply Promotions',
    sendingLabel: 'Envoi automatique…',
    processingLabel: 'Traitement…',
    successTitle: 'Paiement réussi !',
    completeTitle: 'Payment Complete',
    completeMeta: '29 avr. 2026  13:24\nClover Flex •••• 4242',
    viewReceiptLabel: 'Voir le reçu',
    syncedTitle: 'Synchronisé avec Dash',
    syncedNote: 'Paiement enregistré automatiquement',
    chooseTitle: 'Choisissez votre terminal',
    chooseSubtitle: 'Deux options. Entièrement intégrées à Dash.',
    handwrittenNote: 'La même intégration. Choisissez ce qui vous convient.',
    clover: {
      id: 'clover',
      name: 'Clover Flex Gen 4',
      blurb: 'Portable. Puissant. Idéal pour les salons.',
      benefits: [
        'Entièrement intégré à Dash',
        'Tap, puce et débit/crédit',
        'Reçus imprimés ou par e-mail',
        'Rapide et fiable',
      ],
      ctaLabel: 'En savoir plus sur Clover',
      ctaHref: 'https://www.clover.com/',
    },
    poynt: {
      id: 'poynt',
      name: 'Poynt Smart Terminal',
      blurb: 'Intelligent. Flexible. Tout-en-un.',
      benefits: [
        'Entièrement intégré à Dash',
        'Tap, puce et débit/crédit',
        'Imprimante de reçus intégrée',
        'Design moderne et épuré',
        'Idéal pour les salons en croissance',
      ],
      ctaLabel: 'En savoir plus sur Poynt',
      ctaHref: 'https://poynt.com/',
    },
    cloverRentalLabel: 'Location du terminal',
    cloverRentalPrice: '$30 / month',
    cloverRates: ['Debit : 0,04 $ / transaction', 'Crédit : Cost + 0,25 %'],
    noContractLabel: 'Pas de contrat',
    cancelAnytimeLabel: 'Annulation à tout moment',
    ariaLabel: 'Intégration POS avec Clover et Poynt',
  },
  addonFeatures: {
    eyebrow: 'Fonctionnalités add-on',
    titleLead: 'Des add-ons qui rendent la réservation plus',
    titleAccent: 'fluide',
    handwrittenLeft: 'Des outils souples pour le salon',
    handwrittenRight: 'Plus de réservations. Clients plus heureux.',
    giftCard: {
      title: 'Carte cadeau en ligne',
      tagline: 'Achetez en ligne. Envoyez par e-mail. Solde conservé en ligne.',
      steps: [
        { id: 'purchase', label: 'Achat', shortLabel: 'Achat', detail: 'La cliente achète une carte cadeau en ligne.' },
        { id: 'generate', label: 'Créer la carte', shortLabel: 'Créer', detail: 'Une carte cadeau numérique est générée.' },
        { id: 'email', label: 'Envoyer par e-mail', shortLabel: 'Envoyer', detail: 'La carte arrive dans la boîte mail.' },
        { id: 'balance', label: 'Utiliser plus tard', shortLabel: 'Utiliser', detail: 'Le solde est conservé en ligne et utilisé au paiement.' },
      ],
      benefits: [
        { title: 'Envoyée par e-mail', body: 'Livraison instantanée' },
        { title: 'Pas de carte physique', body: '100 % numérique' },
        { title: 'Solde enregistré en ligne', body: 'Toujours accessible' },
      ],
      purchaseTitle: 'Acheter une carte cadeau',
      amountLabel: 'Montant',
      amounts: ['$25', '$50', '$100'],
      selectedAmount: '$50',
      recipientNameLabel: 'Nom du destinataire',
      recipientNamePlaceholder: 'Recipient name',
      recipientEmailLabel: 'E-mail du destinataire',
      recipientEmailPlaceholder: 'name@example.com',
      messageLabel: 'Message (optionnel)',
      messagePlaceholder: 'Happy Birthday!',
      continueLabel: 'Continuer',
      giftCardCaption: 'A gift for you',
      giftCardAmount: '$50',
      giftCardNote: 'Digital. Instant.',
      inboxLabel: 'Boîte de réception',
      inboxTime: 'now',
      inboxTitle: 'A special gift for you',
      inboxAmountLabel: '$50 Gift Card',
      viewGiftCardLabel: 'Voir la carte',
      deliveredLabel: 'Livrée',
      balanceTitle: 'Solde de la carte',
      balanceAmount: '$50.00',
      shopServicesLabel: 'Voir les services',
      applyCheckoutLabel: 'Appliquer au paiement',
      remainingLabel: 'Solde restant',
      remainingAmount: '$25.00',
    },
    deposit: {
      title: 'Acompte en ligne',
      tagline: 'Prenez un acompte en ligne avant le rendez-vous.',
      steps: [
        { id: 'setup', label: 'Réglages', shortLabel: 'Réglages', detail: 'Activez et configurez les acomptes.' },
        { id: 'booking', label: 'La cliente réserve', shortLabel: 'Réserve', detail: 'Un acompte est demandé au paiement.' },
        { id: 'payment', label: 'Paiement de l’acompte', shortLabel: 'Paiement', detail: 'La cliente paie l’acompte en ligne.' },
        { id: 'confirmed', label: 'Réservation confirmée', shortLabel: 'Confirmé', detail: 'Le rendez-vous est sécurisé par l’acompte.' },
      ],
      benefits: [
        { title: 'Moins d’absences', body: 'Revenu plus fiable' },
        { title: 'Réglages souples', body: 'Adapté à votre salon' },
        { title: 'Réservations sécurisées', body: 'Sûr et chiffré' },
      ],
      enableLabel: 'Activer l’acompte en ligne',
      requiredLabel: 'L’acompte est requis pour',
      individualLabel: 'Réservation individuelle',
      groupLabel: 'Réservation de groupe',
      depositAmountLabel: 'Montant de l’acompte',
      depositAmountValue: '50',
      depositRateLabel: 'Taux d’acompte (%)',
      depositRateValue: '25%',
      applyForLabel: 'Appliquer à',
      applyForValue: 'Tous les services',
      bookingTitle: 'Votre réservation',
      bookingEditLabel: 'Modifier',
      serviceName: 'Gel Manicure',
      serviceMeta: '60 min · $120',
      depositRequiredLabel: 'Acompte requis',
      depositRequiredAmount: '$50.00',
      proceedLabel: 'Passer au paiement',
      paymentTitle: 'Paiement',
      secureLabel: 'Paiement sécurisé',
      cardMask: 'Carte se terminant par 4242',
      payDepositAmount: 'Payer 50,00 $ d’acompte',
      payDepositLabel: 'Payer l’acompte',
      paymentNote: 'Votre paiement est sécurisé et chiffré.',
      confirmedTitle: 'Réservation confirmée !',
      confirmedBody: 'Votre rendez-vous est sécurisé par un acompte.',
      viewBookingLabel: 'Voir la réservation',
      addToCalendarLabel: 'Ajouter au calendrier',
    },
    ariaLabel: 'Fonctionnalités optionnelles : cartes cadeaux et acomptes en ligne',
  },
  leadCapture: {
    eyebrow: 'Parler à Dash',
    title: 'Prêt à voir si Dash convient à votre salon ?',
    subtitle: 'Parlez-nous un peu de votre salon. Nous vous montrerons ce qui a du sens pour votre activité.',
    visualHeadlineLead: 'Trouvons la',
    visualHeadlineAccent: 'bonne solution',
    visualHeadlineTail: 'pour votre salon',
    visualBullets: ['Des conseils personnalisés', 'Parler à une vraie personne', 'Sans engagement'],
    visualNote: 'Votre croissance est notre priorité',
    visualBadgeLead: 'Plus de réservations',
    visualBadgeTail: 'Des clients plus heureux',
    tabletAlt: 'Calendrier de rendez-vous Dash Booking sur une tablette',
    phoneAlt: 'Page de réservation Your Lovely Nail Spa sur un téléphone',
    nameLabel: 'Nom complet',
    namePlaceholder: 'Emma Smith',
    businessLabel: 'Nom du salon / de l’entreprise',
    businessPlaceholder: 'Glow Nail Studio',
    addressLabel: 'Adresse',
    addressPlaceholder: '5905 Roblin Blvd',
    regionLabel: 'Province / État',
    regionPlaceholder: 'MB',
    countryLabel: 'Pays',
    countryPlaceholder: 'Canada',
    phoneLabel: 'Téléphone',
    phonePlaceholder: '(204) 555-0100',
    emailLabel: 'Courriel',
    emailPlaceholder: 'emma@example.com',
    cityLabel: 'Ville',
    cityPlaceholder: 'Winnipeg',
    interestLabel: 'Qu’est-ce qui vous intéresse ?',
    interestPlaceholder: 'Choisir',
    messageLabel: 'Message',
    messageHint: 'Facultatif',
    messagePlaceholder: 'Y a-t-il quelque chose que nous devrions savoir ?',
    interestOptions: [
      { value: dashbookingLeadInterestValues[0], label: 'Système de réservation' },
      { value: dashbookingLeadInterestValues[1], label: 'Réceptionniste IA' },
      { value: dashbookingLeadInterestValues[2], label: 'Site web + Google Ads' },
      { value: dashbookingLeadInterestValues[3], label: 'POS' },
      { value: dashbookingLeadInterestValues[4], label: 'Pas encore sûr' },
    ],
    submitLabel: 'Recevoir des conseils pour le salon',
    submittingLabel: 'Envoi…',
    submittedLabel: 'Envoyé',
    successKicker: 'Merci !',
    successTitle: 'Nous avons bien reçu votre demande.',
    successBody: 'Quelqu’un de Dash vous recontactera sous peu.',
    successChips: [
      { title: 'En général sous', body: '1 jour ouvrable' },
      { title: 'Une vraie personne', body: 'vous contactera' },
      { title: 'Des conseils adaptés', body: 'à votre salon' },
    ],
    errorRetry: 'Une erreur s’est produite. Veuillez réessayer.',
    requiredError: 'Ce champ est obligatoire.',
    emailError: 'Veuillez entrer une adresse courriel valide.',
    phoneError: 'Veuillez entrer un numéro de téléphone valide.',
    privacyNote: 'Nous ne partagerons jamais vos informations.',
    ariaLabel: 'Demander conseil à Dash pour votre salon',
  },
  trust: {
    eyebrow: 'Partenaire Google autorisé',
    title: 'Dash Booking - Partenaire direct de Google',
    logoAlt: 'Logo Google',
    partnerCtaLabel: 'Liste des partenaires de réservation Google',
    partnerCtaHref: googlePartnersUrl,
    stats: [
      { value: '160M+', label: 'rendez-vous' },
      { value: '150+', label: 'villes' },
      { value: '16', label: 'pays' },
      { value: '7+', label: 'langues' },
    ],
    statsAriaLabel: 'Statistiques de Dash Booking',
  },
  customerCities: {
    eyebrow: '',
    title: 'Salons qui utilisent Dash Booking',
    cityCta: 'Voir les salons à {city}',
    moreLabel: 'Voir plus de villes',
    lessLabel: 'Voir moins de villes',
  },
  ai: {
    eyebrow: '',
    title: 'Réceptionniste IA intégrée',
    description: 'Répond aux appels et prend les rendez-vous 24/7.',
    supportLine: 'Bilingue anglais-français',
    price: '',
    priceLines: [
      '$300 de configuration unique',
      '$30/mois pour l’accès IA',
      '$20/mois pour le numéro IA',
      '$0.30/minute de temps d’appel',
    ],
    demoTitle: 'Écouter',
    demoIds: [
      'check-current-appoinment',
      'confirm-address',
      'late-appointment',
      'new-appoinment',
      'rescheduling-appoinment',
    ],
  },
  pricing: {
    eyebrow: 'Tarifs',
    title: 'Paiement à l’usage',
    supportLine: 'Pas de frais d’installation. Pas de contrat. Pas de client, pas de frais.',
    volumeLabel: 'Rendez-vous en ligne par mois',
    tiers: [
      {
        range: '0 rendez-vous en ligne complété',
        selectorLabel: '0',
        price: '$0 / month',
        detail: 'Aucun rendez-vous en ligne — aucun frais mensuel',
      },
      {
        range: '1 à 49 rendez-vous en ligne complétés',
        selectorLabel: '<50',
        price: '$29 / month',
        detail: 'Pour 1 à 49 rendez-vous en ligne complétés par mois',
      },
      {
        range: '50 à 149 rendez-vous en ligne complétés',
        selectorLabel: '<150',
        price: '$69 / month',
        detail: 'Pour 50 à 149 rendez-vous en ligne complétés par mois',
      },
      {
        range: '150 à 499 rendez-vous en ligne complétés',
        selectorLabel: '<500',
        price: '$99 / month',
        detail: 'Pour 150 à 499 rendez-vous en ligne complétés par mois',
      },
      {
        range: '500 à 999 rendez-vous en ligne complétés',
        selectorLabel: '<1000',
        price: '$149 / month',
        detail: 'Pour 500 à 999 rendez-vous en ligne complétés par mois',
      },
      {
        range: '1000+ rendez-vous en ligne complétés',
        selectorLabel: '1000+',
        price: '$199 / month',
        detail: 'Pour 1 000+ rendez-vous en ligne complétés par mois',
      },
    ],
    selectorAriaLabel: 'Paliers tarifaires selon le nombre de rendez-vous',
    trustChips: ['Pas de frais d’installation', 'Pas de contrat', 'S’adapte à vos réservations'],
    smsNote: 'Option SMS : 0,05 $ par SMS',
    processingFeeNote: 'Des frais de traitement de 3 % s’appliquent aux paiements par carte de crédit.',
    ctaLabel: '',
  },
  includes: {
    eyebrow: '',
    title: 'Plateforme Dash Booking',
    cardsAriaLabel: 'Fonctionnalités principales de la plateforme Dash Booking',
    cards: [
      {
        title: 'Calendrier de rendez-vous',
        description: 'Gérer le calendrier par jour, employé et source de réservation.',
      },
      {
        title: 'Gestion des clients',
        description: 'Conserver les informations clients, l’historique des réservations et les notes.',
      },
      {
        title: 'Configuration du personnel et des services',
        description: 'Gérer les employés, services, tarifs et durées.',
      },
      {
        title: 'Page de réservation / code QR',
        description: 'Les clients réservent via un lien, un site web ou un code QR.',
      },
      {
        title: 'Réservation de groupe',
        description: 'Prendre plusieurs clients dans une seule réservation.',
      },
      {
        title: 'Rapports et analyses',
        description: 'Suivre les réservations, les revenus et la performance du salon.',
      },
    ],
  },
  addOns: {
    eyebrow: '',
    title: 'Fonctionnalités optionnelles',
    supportLine: '',
    terminalTitle: 'Intégration Clover / Poynt',
    terminalIntro: '',
    terminalBadge: '',
    terminalRates: [
      'Débit : $0.04 / transaction',
      'Crédit : Cost + 0.25%',
      'Location du terminal : $30 / mois',
    ],
    terminalDisclaimer: '',
    terminalListAriaLabel: 'Terminaux de paiement pris en charge',
    optionalListAriaLabel: 'Options disponibles',
    optionalItems: [
      {
        slug: 'website',
        name: 'Site web SEO',
        price: '',
        description: '',
        ctaLabel: 'Modèle',
        ctaHref: 'https://websitetemplate.ca/',
      },
      {
        slug: 'google-business-profile',
        name: 'Gestion de Google Business Profile',
        price: '',
        description: 'Gestion du salon / réponses aux avis Google',
      },
      {
        slug: 'online-deposits-gift-cards',
        name: 'Acomptes en ligne et cartes-cadeaux',
        price: '',
        description: '',
      },
      {
        slug: 'sell-products',
        name: 'Vente de produits',
        price: '',
        description: '',
      },
      {
        slug: 'ai-social-media',
        name: 'IA pour les réseaux sociaux',
        price: '',
        description: 'Bientôt disponible',
      },
    ],
  },
  faq: {
    eyebrow: '',
    title: 'Questions fréquentes',
    items: [
      {
        question: 'Les annulations / no-shows sont-ils facturés ?',
        answer: 'Non.',
      },
      {
        question: 'Puis-je exporter ma liste de clients ?',
        answer: 'Oui. Téléchargement direct en Excel depuis le système.',
      },
      {
        question: 'Puis-je importer des données clients ?',
        answer: 'Oui. Dash Booking aide à les nettoyer et à les importer.',
      },
      {
        question: 'Y a-t-il un contrat ?',
        answer: 'Non. Sans contrat - Sans frais d’installation.',
      },
      {
        question: 'Combien d’employés peuvent l’utiliser ?',
        answer: 'De 1 à plus de 50 employés.',
      },
      {
        question: 'Comment fonctionnent les paiements mensuels ?',
        answer: 'Carte de crédit, chèque annulé ou PayPal.',
      },
      {
        question: 'Quels appareils sont compatibles ?',
        answer: 'Dash Booking fonctionne sur tous les appareils.',
      },
    ],
  },
  footer: {
    summary: 'Plateforme tout-en-un pour salons de beauté',
    rights: '© Dash Booking. Tous droits réservés.',
  },
};
