import type { LandingContent } from '@/content/types';
import { dashbookingLeadInterestValues } from '@/content/lead-capture';
import { googlePartnersUrl } from '@/content/shared';

export const dashbookingLandingContentVi: LandingContent = {
  locale: 'vi',
  metadata: {
    title: 'Dash Booking cho tiệm nail và beauty',
    description: 'Nhận đặt lịch trên Google, quản lý lịch hẹn và chăm sóc khách hàng cùng Dash Booking. Tính phí theo số lịch hẹn online hoàn tất.',
  },
  header: {
    nav: [
      { label: 'Bảng giá', href: '#pricing' },
    ],
    cta: 'Đăng ký miễn phí',
    homeAriaLabel: 'Về trang chủ Dash Booking',
    navAriaLabel: 'Các phần trên trang',
    localeSwitcherAriaLabel: 'Đổi ngôn ngữ',
    partnerPillLabel: 'Xem danh sách đối tác của Google',
  },
  hero: {
    eyebrow: 'Đặt lịch từ Google',
    headlineLead: 'Không có khách,',
    headlineAccent: 'không mất phí.',
    handwrittenNote: 'Phát triển tiệm với Google',
    subtitle:
      'Khách tự đặt lịch trên Google, lịch hẹn tự cập nhật vào Dash. Bạn bớt nghe điện thoại, bớt ghi chép và có thêm thời gian chăm sóc khách.',
    chips: [{ label: 'Đặt lịch trên Google' }, { label: 'Tự cập nhật lịch' }, { label: 'Bớt việc ghi chép' }],
    partnerProofLead: 'Đồng hành cùng hơn',
    partnerProofHighlight: '4.000+',
    partnerProofNoun: 'tiệm',
    partnerProofTail: 'tại',
    partnerProofPlace: 'Mỹ và Canada',
    primaryCta: 'Tư vấn cho tiệm của tôi',
    primaryCtaHref: '#lead-capture',
    toggleWithoutLabel: 'Không có Dash',
    toggleWithLabel: 'Có Dash',
    toggleAriaLabel: 'So sánh đặt lịch khi có và không có Dash',
    previewAriaLabel: 'Minh họa Google và lịch hẹn của tiệm',
    googleIllustrationLabel: 'Minh họa trải nghiệm khách hàng trên Google',
    withoutDashExampleLabel: 'Minh họa tiệm chưa bật đặt lịch online',
    calendarDateLabel: 'T4, 16 thg 9, 2024',
    calendarTodayLabel: 'Hôm nay',
    calendarHeading: 'Lịch hẹn hôm nay',
    emptySlotLabel: 'Trống',
    staff: [
      { id: 'amy', name: 'Amy', role: 'Nail Artist' },
      { id: 'bella', name: 'Bella', role: 'Nail Technician' },
      { id: 'chloe', name: 'Chloe', role: 'Nail Technician' },
    ],
    withoutDash: {
      annotations: [
        { id: 'customer-must-call', title: 'Khách gọi điện đặt lịch', anchor: 'call-button' },
        { id: 'manual-entry', title: 'Tiệm nghe máy và ghi lại lịch hẹn', anchor: 'calendar-empty' },
      ],
    },
    withDash: {
      annotations: [
        { id: 'customer-books-online', title: 'Khách đặt ngay trên Google', anchor: 'book-online' },
        { id: 'appointments-sync', title: 'Lịch hẹn tự cập nhật vào Dash', anchor: 'calendar-fill' },
      ],
    },
    businessProfile: {
      name: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '225',
      category: 'Nail salon',
      hours: 'Open · Closes 7 p.m.',
      address: 'Roblin Blvd 5905 H, Winnipeg, MB R3R 0G8',
      morePhotosLabel: '+12',
      tabs: {
        overview: 'Overview',
        reviews: 'Reviews',
        photos: 'Photos',
        services: 'Services',
      },
      actions: {
        bookOnline: 'Book online',
        website: 'Website',
        directions: 'Directions',
        save: 'Save',
        share: 'Share',
        call: 'Call',
      },
      reviewsRow: '225 Reviews',
    },
  },
  bookingJourney: {
    titleLead: 'Khách đặt lịch.',
    titleAccent: 'Dash lo phần còn lại.',
    handwrittenLeft: 'Bớt việc quản lý lịch.',
    handwrittenRight: 'Nhiều thời gian cho khách.',
    ariaLabel: 'Dash lo từ lúc khách đặt lịch đến lúc khách quay lại',
    muteLabel: 'Tắt tiếng',
    unmuteLabel: 'Bật tiếng',
    nodes: [
      { id: 'discover', title: 'Khách tìm thấy tiệm trên Google', benefit: 'Xem dịch vụ và thông tin của tiệm' },
      { id: 'book-online', title: 'Chọn dịch vụ, chọn giờ, đặt lịch', benefit: 'Không cần gọi điện' },
      { id: 'calendar', title: 'Lịch hẹn tự cập nhật vào Dash', benefit: 'Tiệm không phải nhập lại' },
      { id: 'reminder', title: 'Dash nhắc khách trước giờ hẹn', benefit: 'Giúp khách nhớ lịch' },
      { id: 'completed', title: 'Bạn tập trung chăm sóc khách', benefit: 'Theo dõi lịch ngay trên Dash' },
      { id: 'review', title: 'Dash mời khách đánh giá tiệm', benefit: 'Không cần nhắn từng người' },
      { id: 'growth', title: 'Thêm đánh giá, thêm uy tín', benefit: 'Giúp khách mới yên tâm chọn tiệm' },
    ],
    discover: {
      searchQuery: 'tiệm nail gần tôi',
      salonName: 'Your Lovely Salon',
      ratingValue: '4.8',
      reviewCount: '(225)',
      category: 'Nail Salon',
      hours: 'Open',
    },
    booking: {
      heading: 'Đặt lịch',
      service: 'Gel Manicure',
      staff: 'Nhân viên bất kỳ',
      date: 'T4, 16 thg 9',
      time: '10:00 AM',
      cta: 'Đặt ngay',
    },
    calendar: {
      dateLabel: 'T4, 16 thg 9, 2024',
    },
    reminder: {
      timeLabel: 'Hôm nay 9:00 AM',
      greeting: 'Hi Sarah!',
      body: 'Lịch hẹn của bạn tại Your Lovely Salon là ngày mai lúc 10:00 AM.',
      closing: 'Hẹn gặp bạn!',
      sentLabel: 'Đã gửi nhắc lịch',
    },
    completed: {
      heading: 'Đã hoàn tất!',
      thanks: 'Cảm ơn bạn đã đến Your Lovely Salon!',
      statusLabel: 'Hoàn tất',
    },
    review: {
      timeLabel: 'Hôm nay 2:30 PM',
      message: 'Cảm ơn bạn đã đến! Trải nghiệm tại Your Lovely Salon thế nào?',
      cta: 'Viết đánh giá',
    },
    growth: {
      line1: 'Khách vui',
      line2: 'Đánh giá tốt',
      line3: 'Khách mới tới',
    },
  },
  aiReceptionist: {
    eyebrow: 'AI Receptionist',
    headlineLead: 'Bạn đang làm cho khách?',
    headlineAccent: 'Để Dash nghe máy.',
    subtitle: 'Dash nhận cuộc gọi và đặt lịch giúp tiệm, ngay cả khi bạn đang bận.',
    benefits: [
      { title: 'Hỗ trợ nghe máy 24/7', body: 'Kể cả ngoài giờ và cuối tuần.' },
      { title: 'Nhận lịch hẹn qua điện thoại', body: 'Lịch hẹn được cập nhật ngay vào Dash.' },
      { title: 'Bớt gián đoạn khi làm khách', body: 'Bạn có thể tập trung chăm sóc khách.' },
    ],
    mobileChips: ['Nghe máy 24/7', 'Tự cập nhật lịch hẹn'],
    costTeaser: '',
    costNote: '',
    askLinkLabel: 'Hỏi về AI Receptionist',
    liveCallLabel: 'Nghe cuộc gọi thực tế',
    playRealCallLabel: 'Nghe thử',
    playInvitation: 'Bấm “Nghe thử” để nghe cuộc hội thoại mẫu.',
    pauseLabel: 'Tạm dừng',
    soundOnLabel: 'Bật tiếng',
    soundOffLabel: 'Tắt tiếng',
    customerLabel: 'Khách hàng',
    customerCaption: 'Gọi tới tiệm',
    aiLabel: 'Lễ tân AI Dash',
    aiCaption: 'Nghe máy và hỗ trợ đặt lịch',
    calendarDayLabel: 'Ngày',
    calendarWeekLabel: 'Tuần',
    serviceValue: 'Pedicure',
    anyStaffLabel: 'Nhân viên bất kỳ',
    firstVisitLabel: 'Lần đầu',
    asapLabel: 'Sớm nhất',
    transferLabel: 'Chuyển cuộc gọi cho nhân viên',
    checkingLabel: 'Đang kiểm tra lịch trống',
    availableLabel: 'Còn trống',
    selectedLabel: 'Đã chọn',
    namePendingLabel: 'Khách mới',
    notesNoneLabel: 'Không yêu cầu đặc biệt',
    bookedLabel: 'Đã đặt lịch',
    callCompleteLabel: 'Cuộc gọi kết thúc',
    handwrittenNote: 'Cuộc gọi thành lịch hẹn — tự động!',
    scenariosHeading: 'Nghe thử các tình huống khác',
    scenariosSupport: 'Nghe cách Dash hỗ trợ khách trong từng tình huống.',
    scenariosToggleLabel: 'Nghe thử các tình huống khác',
    scenariosCollapseLabel: 'Thu gọn',
    staff: [
      { id: 'amy', name: 'Amy' },
      { id: 'lisa', name: 'Lisa' },
      { id: 'mai', name: 'Mai' },
    ],
    scenarios: [
      { id: 'check-current-appoinment', title: 'Kiểm tra lịch hẹn', description: 'Tra lịch khách đã đặt.' },
      { id: 'confirm-address', title: 'Hỏi địa chỉ tiệm', description: 'Nói địa chỉ tiệm cho khách.' },
      { id: 'late-appointment', title: 'Báo đến trễ', description: 'Xử lý khi khách đến muộn.' },
      { id: 'rescheduling-appoinment', title: 'Đổi giờ hẹn', description: 'Đổi giờ hẹn giúp khách.' },
    ],
    ariaLabel: 'Demo lễ tân AI Dash nhận cuộc gọi đặt lịch',
  },
  googleReviews: {
    eyebrow: 'Google Reviews',
    headlineLead: 'Trả lời',
    headlineGoogle: 'Google',
    headlineTail: 'Reviews dễ dàng hơn với AI.',
    subtitle: 'Dash hỗ trợ soạn và trả lời đánh giá, giúp tiệm chăm sóc khách cả sau buổi hẹn.',
    benefits: [
      { id: 'auto-reply', title: 'Hỗ trợ trả lời tự động', body: '' },
      { id: 'maps-seo', title: 'Hỗ trợ tối ưu hồ sơ Google Maps', body: '' },
      { id: 'google-connect', title: 'Kết nối với hồ sơ Google của tiệm', body: '' },
      { id: 'included', title: 'Đã có trong Dash', body: 'Không tính thêm phí.' },
    ],
    salonName: 'Your Lovely Salon',
    ratingValue: '4.8',
    reviewCount: '(128 reviews)',
    categoryLocation: 'Beauty Salon · Winnipeg, MB',
    connectedLabel: 'Đã kết nối hồ sơ Google',
    syncLabel: 'Đánh giá được cập nhật tự động',
    reviewsHeading: 'Đánh giá của khách',
    filters: [
      { id: 'all', label: 'Tất cả (128)' },
      { id: 'five', label: '5★ (98)' },
      { id: 'three', label: '3★ (22)' },
      { id: 'one', label: '1★ (8)' },
    ],
    selectedReviewHeading: 'Đánh giá đang xem',
    suggestedReplyHeading: 'Phản hồi gợi ý',
    thinkingLabel: 'Đang soạn phản hồi…',
    replyLabel: 'Gửi phản hồi',
    repliedLabel: 'Đã trả lời',
    copyLabel: 'Sao chép',
    copiedLabel: 'Đã sao chép',
    emptyFilterLabel: 'Chưa có đánh giá mẫu cho mức sao này.',
    previousReviewLabel: 'Đánh giá trước',
    nextReviewLabel: 'Đánh giá sau',
    reviewsAriaLabel: 'Đánh giá Google minh họa',
    ariaLabel: 'Dash hỗ trợ trả lời đánh giá Google bằng AI',
  },
  websiteDesign: {
    eyebrow: 'Phát triển tiệm',
    titleLead: 'Thiết kế website &',
    titleGoogle: 'Google',
    titleTail: 'Ads',
    subtitle: 'Giúp khách tìm hiểu về tiệm và đặt lịch thuận tiện hơn.',
    websiteEyebrow: 'Thiết kế website',
    websiteTitle: 'Một website mang phong cách riêng của tiệm',
    websiteBody: 'Giới thiệu không gian, mẫu nail và dịch vụ của tiệm trên một website có thể nhận đặt lịch.',
    freeSeoLabel: 'SEO miễn phí',
    freeSeoExtra: 'Không phát sinh',
    websiteBullets: [
      'Hình ảnh không gian tiệm',
      'Bộ sưu tập mẫu nail',
      'Danh sách dịch vụ và giá',
      'Đặt lịch trực tuyến',
    ],
    viewMoreLabel: 'Xem thêm website',
    adsEyebrow: 'Quản lý Google Ads',
    adsTitle: 'Hiện lên đầu tiên khi khách tìm “nails near me”',
    adsBody: 'Khi khách tìm “nail salon near me”, quảng cáo giúp tiệm tiếp cận những người đang có nhu cầu. Dash hỗ trợ thiết lập và quản lý chiến dịch.',
    freeSetupLabel: 'Miễn phí thiết lập',
    freeSetupPrice: '$0',
    freeSetupNote: 'Dash hỗ trợ thiết lập và quản lý quảng cáo.',
    creditLabel: 'Spend $600, Get $600',
    creditNote: 'Credit Google Ads miễn phí để bắt đầu',
    searchQuery: 'nail salon near me',
    bookedLabel: 'Đã đặt lịch',
    outcomes: [
      { title: 'Tiếp cận khách quanh tiệm', body: 'Giới thiệu tiệm đến khách trong khu vực' },
      { title: 'Thu hút người đang tìm dịch vụ', body: 'Tiếp cận khách đang có nhu cầu' },
      { title: 'Dẫn khách đến trang đặt lịch', body: 'Đặt lịch thuận tiện từ Google' },
    ],
    galleryTitle: 'Một số website Dash đã làm cho các tiệm',
    gallerySubtitle: 'Xem cách mỗi tiệm giới thiệu phong cách và dịch vụ của mình.',
    viewWebsiteLabel: 'Xem website',
    prevLabel: 'Website trước',
    nextLabel: 'Website sau',
    ariaLabel: 'Thiết kế website và Google Ads',
  },
  posIntegration: {
    eyebrow: 'Kết nối POS',
    titleLead: 'Lên hóa đơn trên Dash.',
    titleAccent: 'Thanh toán trên máy POS.',
    subtitle: 'Số tiền trên hóa đơn được gửi sang Clover hoặc Poynt. Thanh toán xong, Dash tự cập nhật trạng thái.',
    benefits: [
      'Tự gửi số tiền sang máy',
      'Không hợp đồng',
      'Hủy bất cứ lúc nào',
      'Tự cập nhật trạng thái thanh toán',
      'Phù hợp với tiệm',
    ],
    amount: '114.98',
    addPaymentLabel: 'Thanh toán',
    cashLabel: 'Tiền mặt',
    cardLabel: 'Thẻ',
    giftCardLabel: 'Thẻ quà tặng',
    otherLabel: 'Khác',
    loyaltyLabel: 'Dùng điểm tích lũy',
    promotionsLabel: 'Áp dụng ưu đãi',
    sendingLabel: 'Đang gửi sang máy…',
    processingLabel: 'Đang xử lý…',
    successTitle: 'Thanh toán thành công!',
    completeTitle: 'Đã thanh toán',
    completeMeta: '29 thg 4, 2026  13:24\nClover Flex •••• 4242',
    viewReceiptLabel: 'Xem biên lai',
    syncedTitle: 'Đã cập nhật vào Dash',
    syncedNote: 'Giao dịch được lưu tự động',
    chooseTitle: 'Chọn máy phù hợp với tiệm',
    chooseSubtitle: 'Clover và Poynt đều kết nối trực tiếp với Dash.',
    handwrittenNote: 'Chọn thiết bị phù hợp với cách tiệm vận hành.',
    clover: {
      id: 'clover',
      name: 'Clover Flex Gen 4',
      blurb: 'Gọn nhẹ, tiện sử dụng tại tiệm.',
      benefits: [
        'Tích hợp đầy đủ với Dash',
        'Nhận thanh toán chạm, thẻ chip, debit và credit',
        'In biên lai hoặc gửi qua email',
        'Nhanh và ổn định',
      ],
      ctaLabel: 'Tìm hiểu Clover',
      ctaHref: 'https://www.clover.com/',
    },
    poynt: {
      id: 'poynt',
      name: 'Poynt Smart Terminal',
      blurb: 'Thanh toán và in biên lai trên cùng một thiết bị.',
      benefits: [
        'Tích hợp đầy đủ với Dash',
        'Nhận thanh toán chạm, thẻ chip, debit và credit',
        'Tích hợp máy in biên lai',
        'Thiết kế gọn, hiện đại',
        'Phù hợp với tiệm đang mở rộng',
      ],
      ctaLabel: 'Tìm hiểu Poynt',
      ctaHref: 'https://poynt.com/',
    },
    cloverRentalLabel: 'Thuê máy',
    cloverRentalPrice: '$30 / tháng',
    cloverRates: ['Debit: $0.04 / giao dịch', 'Credit: Cost + 0.25%'],
    noContractLabel: 'Không hợp đồng',
    cancelAnytimeLabel: 'Hủy bất cứ lúc nào',
    ariaLabel: 'Tích hợp POS với Clover và Poynt',
  },
  addonFeatures: {
    eyebrow: 'Tiện ích bổ sung',
    titleLead: 'Thêm tiện ích',
    titleAccent: 'cho tiệm',
    handwrittenLeft: 'Công cụ linh hoạt cho tiệm',
    handwrittenRight: 'Đặt lịch thuận tiện hơn cho khách.',
    giftCard: {
      title: 'Online Gift Card',
      tagline: 'Khách mua trực tuyến và gửi qua email. Tiệm theo dõi số dư ngay trên Dash.',
      steps: [
        { id: 'purchase', label: 'Mua', shortLabel: 'Mua', detail: 'Khách mua thẻ quà tặng trực tuyến.' },
        { id: 'generate', label: 'Tạo thẻ quà tặng', shortLabel: 'Tạo', detail: 'Thẻ quà tặng được tạo ngay.' },
        { id: 'email', label: 'Gửi qua email', shortLabel: 'Gửi', detail: 'Thẻ quà tặng được gửi qua email.' },
        { id: 'balance', label: 'Dùng sau', shortLabel: 'Dùng', detail: 'Số dư được lưu để dùng khi thanh toán.' },
      ],
      benefits: [
        { title: 'Gửi bằng email', body: 'Gửi trực tiếp cho người nhận' },
        { title: 'Không cần thẻ giấy', body: 'Lưu trên hệ thống' },
        { title: 'Số dư lưu online', body: 'Dễ dàng theo dõi' },
      ],
      purchaseTitle: 'Mua thẻ quà tặng',
      amountLabel: 'Mệnh giá',
      amounts: ['$25', '$50', '$100'],
      selectedAmount: '$50',
      recipientNameLabel: 'Tên người nhận',
      recipientNamePlaceholder: 'Tên người nhận',
      recipientEmailLabel: 'Email người nhận',
      recipientEmailPlaceholder: 'name@example.com',
      messageLabel: 'Lời nhắn (tuỳ chọn)',
      messagePlaceholder: 'Chúc mừng sinh nhật!',
      continueLabel: 'Tiếp tục',
      giftCardCaption: 'Món quà dành cho bạn',
      giftCardAmount: '$50',
      giftCardNote: 'Thẻ điện tử, gửi qua email.',
      inboxLabel: 'Hộp thư',
      inboxTime: 'Vừa xong',
      inboxTitle: 'Bạn có một món quà đặc biệt',
      inboxAmountLabel: 'Thẻ quà tặng $50',
      viewGiftCardLabel: 'Xem thẻ quà tặng',
      deliveredLabel: 'Đã gửi',
      balanceTitle: 'Số dư còn lại',
      balanceAmount: '$50.00',
      shopServicesLabel: 'Xem dịch vụ',
      applyCheckoutLabel: 'Dùng khi thanh toán',
      remainingLabel: 'Số dư còn lại',
      remainingAmount: '$25.00',
    },
    deposit: {
      title: 'Auto Deposit',
      tagline: 'Cho phép khách thanh toán trước một phần chi phí khi đặt lịch, giúp hạn chế tình trạng đặt rồi không đến.',
      steps: [
        { id: 'setup', label: 'Cài đặt', shortLabel: 'Cài đặt', detail: 'Cài đặt tiền cọc cho lịch hẹn.' },
        { id: 'booking', label: 'Khách đặt lịch', shortLabel: 'Đặt lịch', detail: 'Khách được yêu cầu đặt cọc khi đặt lịch.' },
        { id: 'payment', label: 'Thanh toán cọc', shortLabel: 'Cọc', detail: 'Khách thanh toán tiền cọc trực tuyến.' },
        { id: 'confirmed', label: 'Đã xác nhận', shortLabel: 'Xong', detail: 'Lịch hẹn được xác nhận sau khi đặt cọc.' },
      ],
      benefits: [
        { title: 'Hạn chế khách không đến', body: 'Giúp tiệm chủ động hơn' },
        { title: 'Cài đặt linh hoạt', body: 'Phù hợp với nhu cầu của tiệm' },
        { title: 'Thanh toán bảo mật', body: 'Thông tin được mã hóa' },
      ],
      enableLabel: 'Bật Auto Deposit',
      requiredLabel: 'Yêu cầu đặt cọc cho',
      individualLabel: 'Lịch hẹn cá nhân',
      groupLabel: 'Lịch hẹn nhóm',
      depositAmountLabel: 'Số tiền cọc',
      depositAmountValue: '50',
      depositRateLabel: 'Tỷ lệ cọc (%)',
      depositRateValue: '25%',
      applyForLabel: 'Áp dụng cho',
      applyForValue: 'Tất cả dịch vụ',
      bookingTitle: 'Lịch hẹn của bạn',
      bookingEditLabel: 'Sửa',
      serviceName: 'Gel Manicure',
      serviceMeta: '60 min · $120',
      depositRequiredLabel: 'Cần đặt cọc',
      depositRequiredAmount: '$50.00',
      proceedLabel: 'Thanh toán tiền cọc',
      paymentTitle: 'Thanh toán',
      secureLabel: 'Thanh toán bảo mật',
      cardMask: 'Thẻ có số cuối 4242',
      payDepositAmount: 'Thanh toán cọc $50.00',
      payDepositLabel: 'Thanh toán tiền cọc',
      paymentNote: 'Thanh toán được mã hoá an toàn.',
      confirmedTitle: 'Đã xác nhận lịch hẹn',
      confirmedBody: 'Tiệm đã nhận tiền cọc và xác nhận lịch hẹn.',
      viewBookingLabel: 'Xem lịch hẹn',
      addToCalendarLabel: 'Thêm vào lịch',
    },
    ariaLabel: 'Tính năng add-on gift card và đặt cọc online',
  },
  leadCapture: {
    eyebrow: 'Nói chuyện với Dash',
    title: 'Cùng tìm giải pháp phù hợp với tiệm bạn.',
    subtitle: 'Để lại thông tin, đội ngũ Dash sẽ liên hệ để tìm hiểu nhu cầu và tư vấn cho tiệm.',
    visualHeadlineLead: 'Cùng tìm',
    visualHeadlineAccent: 'giải pháp phù hợp',
    visualHeadlineTail: 'với tiệm bạn.',
    visualBullets: ['Tư vấn theo nhu cầu', 'Trao đổi trực tiếp với đội ngũ Dash', 'Không ràng buộc'],
    visualNote: '',
    visualBadgeLead: 'Đặt lịch thuận tiện',
    visualBadgeTail: 'Chăm sóc khách tốt hơn',
    tabletAlt: 'Lịch hẹn Dash Booking trên máy tính bảng',
    phoneAlt: 'Trang đặt lịch Your Lovely Nail Spa trên điện thoại',
    nameLabel: 'Họ và tên',
    namePlaceholder: 'Emma Smith',
    businessLabel: 'Tên tiệm / Doanh nghiệp',
    businessPlaceholder: 'Glow Nail Studio',
    addressLabel: 'Địa chỉ',
    addressPlaceholder: '5905 Roblin Blvd',
    regionLabel: 'Tỉnh / Bang',
    regionPlaceholder: 'MB',
    countryLabel: 'Quốc gia',
    countryPlaceholder: 'Canada',
    phoneLabel: 'Số điện thoại',
    phonePlaceholder: '(204) 555-0100',
    emailLabel: 'Email',
    emailPlaceholder: 'emma@example.com',
    cityLabel: 'Thành phố',
    cityPlaceholder: 'Winnipeg',
    interestLabel: 'Bạn muốn tìm hiểu về dịch vụ nào?',
    interestPlaceholder: 'Chọn một mục',
    messageLabel: 'Lời nhắn',
    messageHint: 'Không bắt buộc',
    messagePlaceholder: 'Bạn muốn team Dash biết thêm gì trước khi gọi?',
    interestOptions: [
      { value: dashbookingLeadInterestValues[0], label: 'Hệ thống đặt lịch' },
      { value: dashbookingLeadInterestValues[1], label: 'AI Receptionist' },
      { value: dashbookingLeadInterestValues[2], label: 'Website & Google Ads' },
      { value: dashbookingLeadInterestValues[3], label: 'Máy thanh toán POS' },
      { value: dashbookingLeadInterestValues[4], label: 'Tôi cần tư vấn thêm' },
    ],
    submitLabel: 'Tư vấn cho tiệm của tôi',
    submittingLabel: 'Đang gửi…',
    submittedLabel: 'Đã gửi',
    successKicker: 'Cảm ơn!',
    successTitle: 'Dash đã nhận được thông tin.',
    successBody: 'Đội ngũ tư vấn sẽ sớm liên hệ với bạn.',
    successChips: [
      { title: 'Thường trong', body: '1 ngày làm việc' },
      { title: 'Người thật', body: 'sẽ liên hệ bạn' },
      { title: 'Tư vấn riêng', body: 'cho tiệm của bạn' },
    ],
    errorRetry: 'Có lỗi xảy ra. Vui lòng thử lại.',
    requiredError: 'Vui lòng điền thông tin này.',
    emailError: 'Vui lòng nhập email hợp lệ.',
    phoneError: 'Vui lòng nhập số điện thoại hợp lệ.',
    privacyNote: 'Chúng tôi không chia sẻ thông tin của bạn.',
    ariaLabel: 'Nhận tư vấn Dash cho tiệm',
  },
  trust: {
    eyebrow: 'Google Authorized Partner',
    title: 'Dash Booking - Đối tác trực tiếp của Google',
    logoAlt: 'Google logo',
    partnerCtaLabel: 'Danh sách đối tác đặt hẹn của Google',
    partnerCtaHref: googlePartnersUrl,
    stats: [
      { value: '160M+', label: 'lượt đặt hẹn' },
      { value: '150+', label: 'thành phố' },
      { value: '16', label: 'quốc gia' },
      { value: '7+', label: 'ngôn ngữ' },
    ],
    statsAriaLabel: 'Các số liệu của Dash Booking',
  },
  customerCities: {
    eyebrow: '',
    title: 'Các tiệm đang dùng Dash',
    cityCta: 'Xem tiệm ở {city}',
    moreLabel: 'Xem thêm thành phố',
    lessLabel: 'Thu gọn',
  },
  ai: {
    eyebrow: '',
    title: 'Tích hợp AI Receptionist',
    description: 'Chuyên nghe phone book hẹn 24/7',
    supportLine: 'Song ngữ Anh Pháp',
    price: '',
    priceLines: [
      '$300 setup one-time',
      '$30/tháng AI Access',
      '$20/tháng AI Phone Number',
      '$0.30/phút Call Time',
    ],
    demoTitle: 'Nghe thử',
    demoIds: [
      'check-current-appoinment',
      'confirm-address',
      'late-appointment',
      'new-appoinment',
      'rescheduling-appoinment',
    ],
  },
  pricing: {
    eyebrow: 'Bảng giá',
    title: 'Pay As You Go',
    supportLine: 'Không phí thiết lập. Không hợp đồng ràng buộc. Không có lịch hẹn online hoàn tất thì không tính phí tháng.',
    volumeLabel: 'Số lịch hẹn online hoàn tất mỗi tháng',
    tiers: [
      {
        range: '0 lịch hẹn online hoàn tất',
        selectorLabel: '0',
        price: '$0 / tháng',
        detail: 'Chưa có lịch hẹn online hoàn tất — không tính phí tháng',
      },
      {
        range: '1–49 lịch hẹn online hoàn tất',
        selectorLabel: '<50',
        price: '$29 / tháng',
        detail: '1–49 lịch hẹn online hoàn tất mỗi tháng',
      },
      {
        range: '50–149 lịch hẹn online hoàn tất',
        selectorLabel: '<150',
        price: '$69 / tháng',
        detail: '50–149 lịch hẹn online hoàn tất mỗi tháng',
      },
      {
        range: '150–499 lịch hẹn online hoàn tất',
        selectorLabel: '<500',
        price: '$99 / tháng',
        detail: '150–499 lịch hẹn online hoàn tất mỗi tháng',
      },
      {
        range: '500–999 lịch hẹn online hoàn tất',
        selectorLabel: '<1000',
        price: '$149 / tháng',
        detail: '500–999 lịch hẹn online hoàn tất mỗi tháng',
      },
      {
        range: '1.000+ lịch hẹn online hoàn tất',
        selectorLabel: '1000+',
        price: '$199 / tháng',
        detail: '1.000+ lịch hẹn online hoàn tất mỗi tháng',
      },
    ],
    selectorAriaLabel: 'Các mức giá theo số lịch hẹn hoàn tất',
    trustChips: ['Không phí thiết lập', 'Không hợp đồng', 'Tính theo số lịch hoàn tất'],
    smsNote: 'Tin nhắn SMS tùy chọn: 5 cent/tin',
    processingFeeNote: 'Phí xử lý 3% áp dụng khi thanh toán bằng thẻ tín dụng.',
    ctaLabel: '',
  },
  includes: {
    eyebrow: '',
    title: 'Dash Booking Platform',
    cardsAriaLabel: 'Các phần chính của Dash Booking Platform',
    cards: [
      {
        title: 'Appointment Calendar',
        description: 'Quản lý lịch theo ngày, theo thợ, theo nguồn booking.',
      },
      {
        title: 'Client Management',
        description: 'Lưu thông tin khách, lịch sử đặt hẹn và ghi chú.',
      },
      {
        title: 'Staff & Service Setup',
        description: 'Quản lý thợ, dịch vụ, giá và thời gian làm.',
      },
      {
        title: 'Booking Page / QR Code',
        description: 'Khách đặt lịch qua link booking, website hoặc QR code.',
      },
      {
        title: 'Lịch hẹn nhóm',
        description: 'Nhận nhiều khách trong cùng một booking.',
      },
      {
        title: 'Reporting & Analytics',
        description: 'Theo dõi booking, doanh thu và hiệu suất tiệm.',
      },
    ],
  },
  addOns: {
    eyebrow: '',
    title: 'Optional Tiện ích bổ sung',
    supportLine: '',
    terminalTitle: 'Tích hợp Clover / Poynt',
    terminalIntro: '',
    terminalBadge: '',
    terminalRates: ['Debit: $0.04 / giao dịch', 'Credit: Cost + 0.25%', 'Thuê máy: $30 / tháng'],
    terminalDisclaimer: '',
    terminalListAriaLabel: 'Các máy thanh toán được hỗ trợ',
    optionalListAriaLabel: 'Các add-on tùy chọn',
    optionalItems: [
      {
        slug: 'website',
        name: 'SEO Website',
        price: '',
        description: '',
        ctaLabel: 'Template',
        ctaHref: 'https://websitetemplate.ca/',
      },
      {
        slug: 'google-business-profile',
        name: 'Manage Google Business Profile',
        price: '',
        description: 'Quản lý tiệm / trả lời google review',
      },
      {
        slug: 'online-deposits-gift-cards',
        name: 'Auto Deposits & Gift Cards',
        price: '',
        description: '',
      },
      {
        slug: 'sell-products',
        name: 'Bán products',
        price: '',
        description: '',
      },
      {
        slug: 'ai-social-media',
        name: 'AI Social Media',
        price: '',
        description: 'Coming soon',
      },
    ],
  },
  faq: {
    eyebrow: '',
    title: 'Bạn muốn biết thêm?',
    items: [
      {
        question: 'Khách hủy lịch hoặc không đến thì Dash có tính phí không?',
        answer: 'Không. Những lịch hẹn này không được tính vào số lịch hoàn tất để tính phí Dash.',
      },
      {
        question: 'Tôi có thể tải danh sách khách hàng về không?',
        answer: 'Có. Bạn có thể tải danh sách dưới dạng Excel ngay trong hệ thống.',
      },
      {
        question: 'Tôi đã có danh sách khách hàng, có chuyển sang Dash được không?',
        answer: 'Có. Dash hỗ trợ xử lý và nhập danh sách khách hàng vào hệ thống.',
      },
      {
        question: 'Có phải ký hợp đồng không?',
        answer: 'Không. Hệ thống đặt lịch không yêu cầu hợp đồng ràng buộc và không thu phí thiết lập.',
      },
      {
        question: 'Tiệm ít thợ có dùng được không?',
        answer: 'Có. Dash phù hợp với tiệm từ một thợ đến tiệm có nhiều nhân viên.',
      },
      {
        question: 'Tôi có thể thanh toán phí hằng tháng bằng cách nào?',
        answer: 'Bằng thẻ tín dụng, Void Cheque hoặc PayPal.',
      },
      {
        question: 'Tôi có thể dùng Dash trên thiết bị nào?',
        answer: 'Bạn có thể dùng Dash trên điện thoại, máy tính bảng và máy tính.',
      },
    ],
  },
  footer: {
    summary: 'Đặt lịch và quản lý tiệm, cùng Dash Booking.',
    rights: '© Dash Booking. Bảo lưu mọi quyền.',
  },
};
